---
apiVersion: batch/v1
kind: Job
metadata:
  name: laser-polio-worker
spec:
  ttlSecondsAfterFinished: 120
  parallelism: 4
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: laser-polio-worker
          image: idm-docker-staging.packages.idmod.org/laser/laser-polio:latest
          imagePullPolicy: Always
          command:
            - python3
            - calibrate.py
            - "--study-name"
            - "${STUDY_NAME}"
            - "--num-trials"
            - "${NUM_TRIALS}"
          envFrom:
            - secretRef:
                name: mysql-secrets
          resources:
            requests:
              cpu: "6"
            limits:
              cpu: "8"
          env:
          - name: NUMBA_NUM_THREADS
            value: "8"
      imagePullSecrets:
        - name: idmodregcred3
      nodeSelector:
        agentpool: general
